# -*- coding: utf-8 -*-
"""Student_grade_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ge_Je5oK-z5SkZ61VYjKBmj6XSAPcYFC
"""

def grade_calculator(marks):
  if marks>=90 and marks<=100:
    return "A","Excellent Work. You have performed exponentially well.keep aiming high."
  elif marks>=80 and marks<=89:
    return "B","Great Job .keep it up"
  elif marks>=70 and marks<=79:
    return "C","Good work! Keep practicing .you can achieve even more "
  elif marks>=60 and marks<=69:
    return "D","Don't Give up.keep doing "
  else:
    return "F","Better luck next time"

name=input("enter your name : ")
grade=""
comment=""
while True:
  marks=float(input("enter the marks : "))
  try:
    if(marks<=100 and marks>=0):
      break
    else:
      print("you have enter invalid marks ! please enter valid marks")
  except ValueError:
    print("invalid number")

grade,comment=grade_calculator(marks)
print(f"welcome mr/mis {name}")
print(f"Here is your marks details and grade:")
print(f"Marks : {marks}/100")
print(f"Grade : {grade}")
print(comment)



